# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zg3B-5sqmtxelbNFNbkZAJMzX75iu6B0
"""

# Programa: Sistema básico de alquiler de maquinaria
# Empresa: ConstruRent

import streamlit as st
import pandas as pd

st.title("Predicción de Inventario")

uploaded_file = st.file_uploader("Carga tu archivo CSV", type=["csv"])
if uploaded_file:
    df = pd.read_csv(uploaded_file)
    st.write("Datos cargados:")
    st.dataframe(df)
    # Aquí puedes aplicar tu modelo de predicción


# Importamos la librería pandas para manejar la base de datos
import pandas as pd

# Mostramos los primeros registros para verificar la estructura
print("Vista previa de la base de datos:")
print(df.head())

# Extraemos los tipos únicos de maquinaria disponibles
tipos_maquinaria = df["Product ID"].unique()
print("\nTipos de maquinaria disponibles para alquiler:")
for i, tipo in enumerate(tipos_maquinaria):
    print(f"{i + 1}. {tipo}")

# Entrada de datos por parte del usuario
print("\n--- Registro de nuevo alquiler ---")
cliente = input("Ingrese el nombre del cliente: ")

# Mostramos el menú de selección de maquinaria
opcion = int(input("Seleccione el número correspondiente al tipo de maquinaria: "))
tipo_seleccionado = tipos_maquinaria[opcion - 1]

# Solicitamos la cantidad de días de alquiler
dias = int(input("Ingrese la cantidad de días de alquiler: "))

# Asignamos tarifas estimadas por tipo de maquinaria
tarifas_estimadas = {
    "100001093": 50.000,
    "100001095": 40.000,
    "100001103": 30.000,
    "100001104": 60.000,
    "100007070": 70.000,
    "100007664": 90.000,
    "100007805": 100.000,
    "100010579": 45.000,
    "100010587": 55.000,
    "100010849": 60.000,
    "100012519": 40.000,
    "100012881": 60.000,
    "100013997": 20.000,
    "100014325": 30.000,
    "100014496": 50.000,
    "100016703": 60.000,
    "100017262": 30.000,
} # Added the closing curly brace here

# Verificamos si hay tarifa estimada para ese tipo
if str(tipo_seleccionado) in tarifas_estimadas:
    tarifa_diaria = tarifas_estimadas[str(tipo_seleccionado)]
    costo_total = tarifa_diaria * dias

    # Mostrar resumen
    print("\n--- Resumen del alquiler ---")
    print(f"Cliente: {cliente}")
    print(f"Máquina alquilada: {tipo_seleccionado}")
    print(f"Días de alquiler: {dias}")
    print(f"Tarifa diaria estimada: ${tarifa_diaria:.2f}")
    print(f"Costo total del alquiler: ${costo_total:.2f}")
else:
    print("No se encontró una tarifa estimada para este tipo de maquinaria.")

# Mensaje final
print("\nGracias por usar el sistema de alquiler de ConstruRent.")

"""```pseudocode
PROGRAMA Sistema Básico de Alquiler de Maquinaria

    IMPORTAR librería para manejo de datos (pandas)

    DEFINIR ruta del archivo de datos históricos
    CARGAR datos desde el archivo CSV en una estructura de datos (DataFrame)

    MOSTRAR "Vista previa de la base de datos:"
    IMPRIMIR las primeras filas de la estructura de datos

    OBTENER tipos únicos de maquinaria (Product ID) desde la estructura de datos
    MOSTRAR "Tipos de maquinaria disponibles para alquiler:"
    PARA CADA tipo de maquinaria en la lista de tipos únicos CON índice
        IMPRIMIR el número de opción y el tipo de maquinaria

    MOSTRAR "--- Registro de nuevo alquiler ---"
    SOLICITAR al usuario el nombre del cliente y ALMACENARLO

    MOSTRAR el menú de selección de maquinaria
    SOLICITAR al usuario seleccionar el número de opción y ALMACENARLO
    OBTENER el tipo de maquinaria seleccionado usando el índice ingresado por el usuario

    SOLICITAR al usuario la cantidad de días de alquiler y ALMACENARLA

    DEFINIR un diccionario con tarifas estimadas por tipo de maquinaria

    VERIFICAR si el tipo de maquinaria seleccionado tiene una tarifa estimada en el diccionario
        SI existe la tarifa estimada:
            OBTENER la tarifa diaria estimada para el tipo seleccionado
            CALCULAR el costo total multiplicando la tarifa diaria por los días de alquiler

            MOSTRAR "--- Resumen del alquiler ---"
            IMPRIMIR el nombre del cliente
            IMPRIMIR la máquina alquilada
            IMPRIMIR la cantidad de días de alquiler
            IMPRIMIR la tarifa diaria estimada formateada
            IMPRIMIR el costo total del alquiler formateado
        SINO (no existe la tarifa estimada):
            MOSTRAR "No se encontró una tarifa estimada para este tipo de maquinaria."

    MOSTRAR "Gracias por usar el sistema de alquiler de ConstruRent."

FIN PROGRAMA
"""
